### ISSUE TITLE
Error with getPrefix() - infinite loop

### ISSUE THREAD

**Issue by craigpearson** [benjamincrozat/bem-walker-nav-menu#2]
When extending the walker and adding a prefix class the maximum nested items is reached due to the return at https://github.com/benjamincrozat/bem-walker-nav-menu/blob/0b191a43498075acfe4d4b7e4cc949746bd8752d/plugin.php#L136

PR for fix: https://github.com/benjamincrozat/bem-walker-nav-menu/pull/1

**Comment by benjamincrozat** [comment]
Hello,

Thanks for your feedback, I'll take a look after work and will eventually add unit tests if possible to avoid any further issues.

**Comment by benjamincrozat** [comment]
Nevermind, you fixed anyways! Sorry for that, I was probably drunk or something.

**Comment by craigpearson** [comment]
@benjamincrozat Great work! I'm going to adapt this and move it to a package so this can be used as a theme dependency as opposed to a plugin, if you don't mind

Thanks again 🍻
